### ISSUE TITLE
Makefile Error

### ISSUE THREAD

**Issue by toNeptune9** [artursg/golfcart#1]
Hello. 
I have a trouble when i am trying to build your ROS package.
My ROS configuration is - ROS Kinetic (Linux Ubuntu 16.04 LTS)

The problem is:
`catkin_make` Error when building `golfcart/golfcart_gazebo/src/odom_transformation_node.cpp`

Here is a log file:
[make.log](https://github.com/artursg/golfcart/files/2187768/make.log)

**Comment by artursg** [comment]
Check latest commit.
